// Outputs screen — saved filled scripts / pasted generator output blocks,
// stored and shown verbatim. Extracted from app.ts as part of splitting the
// UI layer into smaller modules — no behavior change, same markup/
// data-action/data-bind wiring as before; only renderOutputs() is used
// outside this module (by app.ts's render() dispatcher).

import type { ImportedTextBlock } from '../core/types.js';
import { escapeHtml, attr } from './dom.js';
import { opt, lineNumberView } from './viewModels.js';
import { state } from './state.js';
import { numberLines } from '../core/normalize.js';
import { SOURCE_TYPE_LABELS, SELECTABLE_SOURCE_TYPES, SOURCE_FIELD_MAX } from '../core/sources.js';

function sourceTypeSelect(b: ImportedTextBlock): string {
  const opts = SELECTABLE_SOURCE_TYPES.map((t) => opt(t, SOURCE_TYPE_LABELS[t], b.source.type)).join('');
  return `<select data-bind="source.type" data-id="${attr(b.id)}" aria-label="Source type">${opts}</select>`;
}

function externalToolFields(b: ImportedTextBlock): string {
  const s = b.source;
  return `<div class="card ext-tool">
    <p class="muted"><strong>This app does not run external tools. Paste or import text manually.</strong> The fields below only document the tool for provenance; they are never executed, fetched, or parsed.</p>
    <div class="grid2">
      <div><label>Tool name</label><input type="text" data-bind="source.toolName" data-id="${attr(b.id)}" value="${attr(s.toolName ?? '')}" aria-label="Tool name" maxlength="${SOURCE_FIELD_MAX.toolName}" /></div>
      <div><label>Tool version</label><input type="text" data-bind="source.toolVersion" data-id="${attr(b.id)}" value="${attr(s.toolVersion ?? '')}" aria-label="Tool version" maxlength="${SOURCE_FIELD_MAX.toolVersion}" /></div>
    </div>
    <label>Tool URL (documentation only — the app does not open or fetch it)</label>
    <input type="text" data-bind="source.toolUrl" data-id="${attr(b.id)}" value="${attr(s.toolUrl ?? '')}" aria-label="Tool URL" maxlength="${SOURCE_FIELD_MAX.toolUrl}" />
    <label>Invocation notes</label>
    <textarea class="prose" data-bind="source.invocationNotes" data-id="${attr(b.id)}" placeholder="How the tool was run, for your records (not executed)" aria-label="Invocation notes" maxlength="${SOURCE_FIELD_MAX.invocationNotes}">${escapeHtml(s.invocationNotes ?? '')}</textarea>
  </div>`;
}

function renderBlock(b: ImportedTextBlock): string {
  const collapsed = state.collapsed.has(b.id);
  const editing = state.blockEdit.has(b.id) || b.rawText === '';
  const lineCount = numberLines(b.rawText).length;

  const s = b.source;
  const provLine = `Source: <strong>${escapeHtml(SOURCE_TYPE_LABELS[s.type])}</strong> · imported ${escapeHtml(s.importedAt)}${s.filename ? ' · file: ' + escapeHtml(s.filename) : ''}${s.actionLabel ? ' · action: ' + escapeHtml(s.actionLabel) : ''}${s.generatedBy ? ' · generated by ' + escapeHtml(s.generatedBy) : ''}`;

  const bodyInner = collapsed
    ? ''
    : `<div class="prov"><span class="muted">${provLine}</span></div>
      <div class="grid2">
        <div><label>Source type</label>${sourceTypeSelect(b)}</div>
        <div><label>Source label</label><input type="text" data-bind="source.label" data-id="${attr(b.id)}" value="${attr(s.label)}" aria-label="Source label" maxlength="${SOURCE_FIELD_MAX.label}" /></div>
      </div>
      <label>Source notes</label>
      <input type="text" data-bind="source.notes" data-id="${attr(b.id)}" value="${attr(s.notes ?? '')}" placeholder="Optional notes about the source" aria-label="Source notes" maxlength="${SOURCE_FIELD_MAX.notes}" />
      ${s.type === 'external-local-tool' ? externalToolFields(b) : ''}
      <div class="grid2">
        <div><label>Category label</label><input type="text" data-bind="block.categoryLabel" data-id="${attr(b.id)}" value="${attr(b.categoryLabel)}" aria-label="Category label" /></div>
        <div><label>Revision label</label><input type="text" data-bind="block.revisionLabel" data-id="${attr(b.id)}" value="${attr(b.revisionLabel)}" aria-label="Revision label" /></div>
      </div>
      <label>Block notes</label>
      <input type="text" data-bind="block.notes" data-id="${attr(b.id)}" value="${attr(b.notes)}" placeholder="Optional notes about this block" aria-label="Block notes" />
      <label>Imported text (stored verbatim)</label>
      ${editing
        ? `<textarea data-bind="block.rawText" data-id="${attr(b.id)}" placeholder="Paste pre-existing text here" aria-label="Imported text">${escapeHtml(b.rawText)}</textarea>`
        : lineNumberView(b.rawText)}`;

  return `<div class="card block" data-ref="${attr(b.id)}">
    <div class="row block-head" style="justify-content:space-between">
      <div class="row">
        <button class="icon" data-action="toggle-collapse" data-id="${attr(b.id)}" aria-expanded="${!collapsed}" aria-label="${collapsed ? 'Expand block' : 'Collapse block'}">${collapsed ? '▸' : '▾'}</button>
        <input type="text" data-bind="block.title" data-id="${attr(b.id)}" value="${attr(b.title)}" placeholder="Block title" aria-label="Block title" style="min-width:16rem" />
        <span class="pill">${escapeHtml(SOURCE_TYPE_LABELS[s.type])}</span>
        <span class="muted">${lineCount} line${lineCount === 1 ? '' : 's'}</span>
      </div>
      <div class="row">
        <button class="btn small" data-action="toggle-edit" data-id="${attr(b.id)}">${editing ? 'Done' : 'Edit'}</button>
        <button class="btn small" data-action="copy-block" data-id="${attr(b.id)}" aria-label="Copy raw text">Copy raw</button>
        <button class="btn danger small" data-action="remove-block" data-id="${attr(b.id)}" aria-label="Remove block">Remove</button>
      </div>
    </div>
    ${bodyInner}
  </div>`;
}

export function renderOutputs(): string {
  const p = state.project!;
  const blocks = p.importedBlocks.map(renderBlock).join('');
  return `<h1>Outputs</h1>
    <p class="muted">Text is stored exactly as pasted or loaded. It is never modified or generated; line numbers are display-only and the "Copy raw" button copies the stored text verbatim.</p>
    ${blocks || '<div class="empty">Saved filled scripts and pasted generator output will appear here.</div>'}
    <div class="card">
      <h3>Add a block</h3>
      <div class="grid2">
        <div><label for="nb-title">Title</label><input type="text" id="nb-title" placeholder="Block title" /></div>
        <div><label for="nb-category">Category label</label><input type="text" id="nb-category" /></div>
      </div>
      <label for="nb-text">Text</label>
      <textarea id="nb-text" placeholder="Paste pre-existing text"></textarea>
      <div class="row" style="margin-top:0.5rem">
        <button class="btn" data-action="add-block">Add block</button>
        <button class="btn" data-action="load-block">Load .txt file as block</button>
        <input type="file" accept=".txt,text/plain" data-action="block-file" id="block-file-input" style="display:none" aria-label="Load text file as block" />
      </div>
    </div>`;
}
