// Local, static, checked-in catalog of Generation III move indices — used
// only to make curated-schema "move" fields show a friendly name/value
// dropdown instead of a raw number box.
//
// SOURCE: hand-entered from Bulbapedia's "List of moves" table (the same
// data underlying its "List of moves by index number in Generation III"
// framing), cross-checked against the fixed index boundary points (index
// 100 "Teleport" is the last Generation I move, 101 "Night Shade" begins
// the Generation II additions, 251 "Beat Up" is the last Generation II
// move, and 252 "Fake Out" begins the Generation III originals, ending at
// 354 "Psycho Boost"). This file is NOT fetched, scraped, or generated at
// runtime — it is static source code, reviewed and edited like any other
// file in this repo. It now covers the COMPLETE Generation III move index
// range, values 1-354: this single table is shared, unchanged, across
// Ruby, Sapphire, FireRed, LeafGreen, and Emerald, so it is directly and
// fully usable for FireRed/LeafGreen specifically. Move `category` values
// reflect each move's Generation III elemental type/mechanics — the type
// the game itself actually uses — NOT a later generation's retyping. The
// Fairy type did not exist until Generation VI, so the handful of moves
// later retyped Fairy (Charm, Moonlight, Sweet Kiss) are correctly listed
// here as Normal, matching how FireRed/LeafGreen itself resolves their
// type. Modern/Fairy is still findable by name via each such entry's
// `aliases: ['fairy']`, so searching "fairy" surfaces them without
// misrepresenting their actual in-game category. Treat this as a curated
// reference, not gospel: double-check anything you rely on against your
// own reference before trusting it — this app's scripts and generator
// remain the source of truth, not this catalog.

import type { ReferenceCatalog } from '../core/referenceData.js';

export const GEN3_MOVES_CATALOG: ReferenceCatalog = {
  id: 'gen3-moves',
  label: 'Generation III moves',
  description: 'Move name/index lookup for curated schema "move" fields.',
  partial: false,
  sourceNote:
    'Hand-entered from Bulbapedia\'s "List of moves" table (current revision, ' +
    'fetched July 2026), which documents each move\'s index number and the ' +
    'generation it debuted in. Covers the complete Generation III move index ' +
    'range, values 1-354: indices 1-100 are the Generation I move set, 101-251 ' +
    'are the Generation II additions, and 252-354 are the Generation III ' +
    'originals (Fake Out through Psycho Boost) — this single table is shared, ' +
    'unchanged, across Ruby, Sapphire, FireRed, LeafGreen, and Emerald, so it ' +
    'is safe to treat as complete for FireRed/LeafGreen specifically. Move ' +
    '`category` values are each move\'s Generation III type/mechanics — the ' +
    'type FireRed/LeafGreen itself actually resolves — not a later ' +
    'generation\'s retyping. Charm, Moonlight, and Sweet Kiss are Normal-type ' +
    'in Generation III (the Fairy type did not exist until Generation VI); ' +
    'each carries an `aliases: [\'fairy\']` entry so searching "fairy" still ' +
    'finds them without misrepresenting their actual in-game category.',
  entries: [
    { value: 1, name: 'Pound', category: 'Normal' },
    { value: 2, name: 'Karate Chop', category: 'Fighting' },
    { value: 3, name: 'Double Slap', category: 'Normal' },
    { value: 4, name: 'Comet Punch', category: 'Normal' },
    { value: 5, name: 'Mega Punch', category: 'Normal' },
    { value: 6, name: 'Pay Day', category: 'Normal' },
    { value: 7, name: 'Fire Punch', category: 'Fire' },
    { value: 8, name: 'Ice Punch', category: 'Ice' },
    { value: 9, name: 'Thunder Punch', category: 'Electric' },
    { value: 10, name: 'Scratch', category: 'Normal' },
    { value: 11, name: 'Vice Grip', category: 'Normal' },
    { value: 12, name: 'Guillotine', category: 'Normal' },
    { value: 13, name: 'Razor Wind', category: 'Normal' },
    { value: 14, name: 'Swords Dance', category: 'Normal' },
    { value: 15, name: 'Cut', category: 'Normal' },
    { value: 16, name: 'Gust', category: 'Flying' },
    { value: 17, name: 'Wing Attack', category: 'Flying' },
    { value: 18, name: 'Whirlwind', category: 'Normal' },
    { value: 19, name: 'Fly', category: 'Flying' },
    { value: 20, name: 'Bind', category: 'Normal' },
    { value: 21, name: 'Slam', category: 'Normal' },
    { value: 22, name: 'Vine Whip', category: 'Grass' },
    { value: 23, name: 'Stomp', category: 'Normal' },
    { value: 24, name: 'Double Kick', category: 'Fighting' },
    { value: 25, name: 'Mega Kick', category: 'Normal' },
    { value: 26, name: 'Jump Kick', category: 'Fighting' },
    { value: 27, name: 'Rolling Kick', category: 'Fighting' },
    { value: 28, name: 'Sand Attack', category: 'Ground' },
    { value: 29, name: 'Headbutt', category: 'Normal' },
    { value: 30, name: 'Horn Attack', category: 'Normal' },
    { value: 31, name: 'Fury Attack', category: 'Normal' },
    { value: 32, name: 'Horn Drill', category: 'Normal' },
    { value: 33, name: 'Tackle', category: 'Normal' },
    { value: 34, name: 'Body Slam', category: 'Normal' },
    { value: 35, name: 'Wrap', category: 'Normal' },
    { value: 36, name: 'Take Down', category: 'Normal' },
    { value: 37, name: 'Thrash', category: 'Normal' },
    { value: 38, name: 'Double-Edge', category: 'Normal' },
    { value: 39, name: 'Tail Whip', category: 'Normal' },
    { value: 40, name: 'Poison Sting', category: 'Poison' },
    { value: 41, name: 'Twineedle', category: 'Bug' },
    { value: 42, name: 'Pin Missile', category: 'Bug' },
    { value: 43, name: 'Leer', category: 'Normal' },
    { value: 44, name: 'Bite', category: 'Dark' },
    { value: 45, name: 'Growl', category: 'Normal' },
    { value: 46, name: 'Roar', category: 'Normal' },
    { value: 47, name: 'Sing', category: 'Normal' },
    { value: 48, name: 'Supersonic', category: 'Normal' },
    { value: 49, name: 'Sonic Boom', category: 'Normal' },
    { value: 50, name: 'Disable', category: 'Normal' },
    { value: 51, name: 'Acid', category: 'Poison' },
    { value: 52, name: 'Ember', category: 'Fire' },
    { value: 53, name: 'Flamethrower', category: 'Fire' },
    { value: 54, name: 'Mist', category: 'Ice' },
    { value: 55, name: 'Water Gun', category: 'Water' },
    { value: 56, name: 'Hydro Pump', category: 'Water' },
    { value: 57, name: 'Surf', category: 'Water' },
    { value: 58, name: 'Ice Beam', category: 'Ice' },
    { value: 59, name: 'Blizzard', category: 'Ice' },
    { value: 60, name: 'Psybeam', category: 'Psychic' },
    { value: 61, name: 'Bubble Beam', category: 'Water' },
    { value: 62, name: 'Aurora Beam', category: 'Ice' },
    { value: 63, name: 'Hyper Beam', category: 'Normal' },
    { value: 64, name: 'Peck', category: 'Flying' },
    { value: 65, name: 'Drill Peck', category: 'Flying' },
    { value: 66, name: 'Submission', category: 'Fighting' },
    { value: 67, name: 'Low Kick', category: 'Fighting' },
    { value: 68, name: 'Counter', category: 'Fighting' },
    { value: 69, name: 'Seismic Toss', category: 'Fighting' },
    { value: 70, name: 'Strength', category: 'Normal' },
    { value: 71, name: 'Absorb', category: 'Grass' },
    { value: 72, name: 'Mega Drain', category: 'Grass' },
    { value: 73, name: 'Leech Seed', category: 'Grass' },
    { value: 74, name: 'Growth', category: 'Normal' },
    { value: 75, name: 'Razor Leaf', category: 'Grass' },
    { value: 76, name: 'Solar Beam', category: 'Grass' },
    { value: 77, name: 'Poison Powder', category: 'Poison' },
    { value: 78, name: 'Stun Spore', category: 'Grass' },
    { value: 79, name: 'Sleep Powder', category: 'Grass' },
    { value: 80, name: 'Petal Dance', category: 'Grass' },
    { value: 81, name: 'String Shot', category: 'Bug' },
    { value: 82, name: 'Dragon Rage', category: 'Dragon' },
    { value: 83, name: 'Fire Spin', category: 'Fire' },
    { value: 84, name: 'Thunder Shock', category: 'Electric' },
    { value: 85, name: 'Thunderbolt', category: 'Electric' },
    { value: 86, name: 'Thunder Wave', category: 'Electric' },
    { value: 87, name: 'Thunder', category: 'Electric' },
    { value: 88, name: 'Rock Throw', category: 'Rock' },
    { value: 89, name: 'Earthquake', category: 'Ground' },
    { value: 90, name: 'Fissure', category: 'Ground' },
    { value: 91, name: 'Dig', category: 'Ground' },
    { value: 92, name: 'Toxic', category: 'Poison' },
    { value: 93, name: 'Confusion', category: 'Psychic' },
    { value: 94, name: 'Psychic', category: 'Psychic' },
    { value: 95, name: 'Hypnosis', category: 'Psychic' },
    { value: 96, name: 'Meditate', category: 'Psychic' },
    { value: 97, name: 'Agility', category: 'Psychic' },
    { value: 98, name: 'Quick Attack', category: 'Normal' },
    { value: 99, name: 'Rage', category: 'Normal' },
    { value: 100, name: 'Teleport', category: 'Psychic' },
    { value: 101, name: 'Night Shade', category: 'Ghost' },
    { value: 102, name: 'Mimic', category: 'Normal' },
    { value: 103, name: 'Screech', category: 'Normal' },
    { value: 104, name: 'Double Team', category: 'Normal' },
    { value: 105, name: 'Recover', category: 'Normal' },
    { value: 106, name: 'Harden', category: 'Normal' },
    { value: 107, name: 'Minimize', category: 'Normal' },
    { value: 108, name: 'Smokescreen', category: 'Normal' },
    { value: 109, name: 'Confuse Ray', category: 'Ghost' },
    { value: 110, name: 'Withdraw', category: 'Water' },
    { value: 111, name: 'Defense Curl', category: 'Normal' },
    { value: 112, name: 'Barrier', category: 'Psychic' },
    { value: 113, name: 'Light Screen', category: 'Psychic' },
    { value: 114, name: 'Haze', category: 'Ice' },
    { value: 115, name: 'Reflect', category: 'Psychic' },
    { value: 116, name: 'Focus Energy', category: 'Normal' },
    { value: 117, name: 'Bide', category: 'Normal' },
    { value: 118, name: 'Metronome', category: 'Normal' },
    { value: 119, name: 'Mirror Move', category: 'Flying' },
    { value: 120, name: 'Self-Destruct', category: 'Normal' },
    { value: 121, name: 'Egg Bomb', category: 'Normal' },
    { value: 122, name: 'Lick', category: 'Ghost' },
    { value: 123, name: 'Smog', category: 'Poison' },
    { value: 124, name: 'Sludge', category: 'Poison' },
    { value: 125, name: 'Bone Club', category: 'Ground' },
    { value: 126, name: 'Fire Blast', category: 'Fire' },
    { value: 127, name: 'Waterfall', category: 'Water' },
    { value: 128, name: 'Clamp', category: 'Water' },
    { value: 129, name: 'Swift', category: 'Normal' },
    { value: 130, name: 'Skull Bash', category: 'Normal' },
    { value: 131, name: 'Spike Cannon', category: 'Normal' },
    { value: 132, name: 'Constrict', category: 'Normal' },
    { value: 133, name: 'Amnesia', category: 'Psychic' },
    { value: 134, name: 'Kinesis', category: 'Psychic' },
    { value: 135, name: 'Soft-Boiled', category: 'Normal' },
    { value: 136, name: 'High Jump Kick', category: 'Fighting' },
    { value: 137, name: 'Glare', category: 'Normal' },
    { value: 138, name: 'Dream Eater', category: 'Psychic' },
    { value: 139, name: 'Poison Gas', category: 'Poison' },
    { value: 140, name: 'Barrage', category: 'Normal' },
    { value: 141, name: 'Leech Life', category: 'Bug' },
    { value: 142, name: 'Lovely Kiss', category: 'Normal' },
    { value: 143, name: 'Sky Attack', category: 'Flying' },
    { value: 144, name: 'Transform', category: 'Normal' },
    { value: 145, name: 'Bubble', category: 'Water' },
    { value: 146, name: 'Dizzy Punch', category: 'Normal' },
    { value: 147, name: 'Spore', category: 'Grass' },
    { value: 148, name: 'Flash', category: 'Normal' },
    { value: 149, name: 'Psywave', category: 'Psychic' },
    { value: 150, name: 'Splash', category: 'Normal' },
    { value: 151, name: 'Acid Armor', category: 'Poison' },
    { value: 152, name: 'Crabhammer', category: 'Water' },
    { value: 153, name: 'Explosion', category: 'Normal' },
    { value: 154, name: 'Fury Swipes', category: 'Normal' },
    { value: 155, name: 'Bonemerang', category: 'Ground' },
    { value: 156, name: 'Rest', category: 'Psychic' },
    { value: 157, name: 'Rock Slide', category: 'Rock' },
    { value: 158, name: 'Hyper Fang', category: 'Normal' },
    { value: 159, name: 'Sharpen', category: 'Normal' },
    { value: 160, name: 'Conversion', category: 'Normal' },
    { value: 161, name: 'Tri Attack', category: 'Normal' },
    { value: 162, name: 'Super Fang', category: 'Normal' },
    { value: 163, name: 'Slash', category: 'Normal' },
    { value: 164, name: 'Substitute', category: 'Normal' },
    { value: 165, name: 'Struggle', category: 'Normal' },
    { value: 166, name: 'Sketch', category: 'Normal' },
    { value: 167, name: 'Triple Kick', category: 'Fighting' },
    { value: 168, name: 'Thief', category: 'Dark' },
    { value: 169, name: 'Spider Web', category: 'Bug' },
    { value: 170, name: 'Mind Reader', category: 'Normal' },
    { value: 171, name: 'Nightmare', category: 'Ghost' },
    { value: 172, name: 'Flame Wheel', category: 'Fire' },
    { value: 173, name: 'Snore', category: 'Normal' },
    { value: 174, name: 'Curse', category: 'Ghost' },
    { value: 175, name: 'Flail', category: 'Normal' },
    { value: 176, name: 'Conversion 2', category: 'Normal' },
    { value: 177, name: 'Aeroblast', category: 'Flying' },
    { value: 178, name: 'Cotton Spore', category: 'Grass' },
    { value: 179, name: 'Reversal', category: 'Fighting' },
    { value: 180, name: 'Spite', category: 'Ghost' },
    { value: 181, name: 'Powder Snow', category: 'Ice' },
    { value: 182, name: 'Protect', category: 'Normal' },
    { value: 183, name: 'Mach Punch', category: 'Fighting' },
    { value: 184, name: 'Scary Face', category: 'Normal' },
    { value: 185, name: 'Feint Attack', category: 'Dark' },
    { value: 186, name: 'Sweet Kiss', category: 'Normal', aliases: ['fairy'] },
    { value: 187, name: 'Belly Drum', category: 'Normal' },
    { value: 188, name: 'Sludge Bomb', category: 'Poison' },
    { value: 189, name: 'Mud-Slap', category: 'Ground' },
    { value: 190, name: 'Octazooka', category: 'Water' },
    { value: 191, name: 'Spikes', category: 'Ground' },
    { value: 192, name: 'Zap Cannon', category: 'Electric' },
    { value: 193, name: 'Foresight', category: 'Normal' },
    { value: 194, name: 'Destiny Bond', category: 'Ghost' },
    { value: 195, name: 'Perish Song', category: 'Normal' },
    { value: 196, name: 'Icy Wind', category: 'Ice' },
    { value: 197, name: 'Detect', category: 'Fighting' },
    { value: 198, name: 'Bone Rush', category: 'Ground' },
    { value: 199, name: 'Lock-On', category: 'Normal' },
    { value: 200, name: 'Outrage', category: 'Dragon' },
    { value: 201, name: 'Sandstorm', category: 'Rock' },
    { value: 202, name: 'Giga Drain', category: 'Grass' },
    { value: 203, name: 'Endure', category: 'Normal' },
    { value: 204, name: 'Charm', category: 'Normal', aliases: ['fairy'] },
    { value: 205, name: 'Rollout', category: 'Rock' },
    { value: 206, name: 'False Swipe', category: 'Normal' },
    { value: 207, name: 'Swagger', category: 'Normal' },
    { value: 208, name: 'Milk Drink', category: 'Normal' },
    { value: 209, name: 'Spark', category: 'Electric' },
    { value: 210, name: 'Fury Cutter', category: 'Bug' },
    { value: 211, name: 'Steel Wing', category: 'Steel' },
    { value: 212, name: 'Mean Look', category: 'Normal' },
    { value: 213, name: 'Attract', category: 'Normal' },
    { value: 214, name: 'Sleep Talk', category: 'Normal' },
    { value: 215, name: 'Heal Bell', category: 'Normal' },
    { value: 216, name: 'Return', category: 'Normal' },
    { value: 217, name: 'Present', category: 'Normal' },
    { value: 218, name: 'Frustration', category: 'Normal' },
    { value: 219, name: 'Safeguard', category: 'Normal' },
    { value: 220, name: 'Pain Split', category: 'Normal' },
    { value: 221, name: 'Sacred Fire', category: 'Fire' },
    { value: 222, name: 'Magnitude', category: 'Ground' },
    { value: 223, name: 'Dynamic Punch', category: 'Fighting' },
    { value: 224, name: 'Megahorn', category: 'Bug' },
    { value: 225, name: 'Dragon Breath', category: 'Dragon' },
    { value: 226, name: 'Baton Pass', category: 'Normal' },
    { value: 227, name: 'Encore', category: 'Normal' },
    { value: 228, name: 'Pursuit', category: 'Dark' },
    { value: 229, name: 'Rapid Spin', category: 'Normal' },
    { value: 230, name: 'Sweet Scent', category: 'Normal' },
    { value: 231, name: 'Iron Tail', category: 'Steel' },
    { value: 232, name: 'Metal Claw', category: 'Steel' },
    { value: 233, name: 'Vital Throw', category: 'Fighting' },
    { value: 234, name: 'Morning Sun', category: 'Normal' },
    { value: 235, name: 'Synthesis', category: 'Grass' },
    { value: 236, name: 'Moonlight', category: 'Normal', aliases: ['fairy'] },
    { value: 237, name: 'Hidden Power', category: 'Normal' },
    { value: 238, name: 'Cross Chop', category: 'Fighting' },
    { value: 239, name: 'Twister', category: 'Dragon' },
    { value: 240, name: 'Rain Dance', category: 'Water' },
    { value: 241, name: 'Sunny Day', category: 'Fire' },
    { value: 242, name: 'Crunch', category: 'Dark' },
    { value: 243, name: 'Mirror Coat', category: 'Psychic' },
    { value: 244, name: 'Psych Up', category: 'Normal' },
    { value: 245, name: 'Extreme Speed', category: 'Normal' },
    { value: 246, name: 'Ancient Power', category: 'Rock' },
    { value: 247, name: 'Shadow Ball', category: 'Ghost' },
    { value: 248, name: 'Future Sight', category: 'Psychic' },
    { value: 249, name: 'Rock Smash', category: 'Fighting' },
    { value: 250, name: 'Whirlpool', category: 'Water' },
    { value: 251, name: 'Beat Up', category: 'Dark' },
    { value: 252, name: 'Fake Out', category: 'Normal' },
    { value: 253, name: 'Uproar', category: 'Normal' },
    { value: 254, name: 'Stockpile', category: 'Normal' },
    { value: 255, name: 'Spit Up', category: 'Normal' },
    { value: 256, name: 'Swallow', category: 'Normal' },
    { value: 257, name: 'Heat Wave', category: 'Fire' },
    { value: 258, name: 'Hail', category: 'Ice' },
    { value: 259, name: 'Torment', category: 'Dark' },
    { value: 260, name: 'Flatter', category: 'Dark' },
    { value: 261, name: 'Will-O-Wisp', category: 'Fire' },
    { value: 262, name: 'Memento', category: 'Dark' },
    { value: 263, name: 'Facade', category: 'Normal' },
    { value: 264, name: 'Focus Punch', category: 'Fighting' },
    { value: 265, name: 'Smelling Salts', category: 'Normal' },
    { value: 266, name: 'Follow Me', category: 'Normal' },
    { value: 267, name: 'Nature Power', category: 'Normal' },
    { value: 268, name: 'Charge', category: 'Electric' },
    { value: 269, name: 'Taunt', category: 'Dark' },
    { value: 270, name: 'Helping Hand', category: 'Normal' },
    { value: 271, name: 'Trick', category: 'Psychic' },
    { value: 272, name: 'Role Play', category: 'Psychic' },
    { value: 273, name: 'Wish', category: 'Normal' },
    { value: 274, name: 'Assist', category: 'Normal' },
    { value: 275, name: 'Ingrain', category: 'Grass' },
    { value: 276, name: 'Superpower', category: 'Fighting' },
    { value: 277, name: 'Magic Coat', category: 'Psychic' },
    { value: 278, name: 'Recycle', category: 'Normal' },
    { value: 279, name: 'Revenge', category: 'Fighting' },
    { value: 280, name: 'Brick Break', category: 'Fighting' },
    { value: 281, name: 'Yawn', category: 'Normal' },
    { value: 282, name: 'Knock Off', category: 'Dark' },
    { value: 283, name: 'Endeavor', category: 'Normal' },
    { value: 284, name: 'Eruption', category: 'Fire' },
    { value: 285, name: 'Skill Swap', category: 'Psychic' },
    { value: 286, name: 'Imprison', category: 'Psychic' },
    { value: 287, name: 'Refresh', category: 'Normal' },
    { value: 288, name: 'Grudge', category: 'Ghost' },
    { value: 289, name: 'Snatch', category: 'Dark' },
    { value: 290, name: 'Secret Power', category: 'Normal' },
    { value: 291, name: 'Dive', category: 'Water' },
    { value: 292, name: 'Arm Thrust', category: 'Fighting' },
    { value: 293, name: 'Camouflage', category: 'Normal' },
    { value: 294, name: 'Tail Glow', category: 'Bug' },
    { value: 295, name: 'Luster Purge', category: 'Psychic' },
    { value: 296, name: 'Mist Ball', category: 'Psychic' },
    { value: 297, name: 'Feather Dance', category: 'Flying' },
    { value: 298, name: 'Teeter Dance', category: 'Normal' },
    { value: 299, name: 'Blaze Kick', category: 'Fire' },
    { value: 300, name: 'Mud Sport', category: 'Ground' },
    { value: 301, name: 'Ice Ball', category: 'Ice' },
    { value: 302, name: 'Needle Arm', category: 'Grass' },
    { value: 303, name: 'Slack Off', category: 'Normal' },
    { value: 304, name: 'Hyper Voice', category: 'Normal' },
    { value: 305, name: 'Poison Fang', category: 'Poison' },
    { value: 306, name: 'Crush Claw', category: 'Normal' },
    { value: 307, name: 'Blast Burn', category: 'Fire' },
    { value: 308, name: 'Hydro Cannon', category: 'Water' },
    { value: 309, name: 'Meteor Mash', category: 'Steel' },
    { value: 310, name: 'Astonish', category: 'Ghost' },
    { value: 311, name: 'Weather Ball', category: 'Normal' },
    { value: 312, name: 'Aromatherapy', category: 'Grass' },
    { value: 313, name: 'Fake Tears', category: 'Dark' },
    { value: 314, name: 'Air Cutter', category: 'Flying' },
    { value: 315, name: 'Overheat', category: 'Fire' },
    { value: 316, name: 'Odor Sleuth', category: 'Normal' },
    { value: 317, name: 'Rock Tomb', category: 'Rock' },
    { value: 318, name: 'Silver Wind', category: 'Bug' },
    { value: 319, name: 'Metal Sound', category: 'Steel' },
    { value: 320, name: 'Grass Whistle', category: 'Grass' },
    { value: 321, name: 'Tickle', category: 'Normal' },
    { value: 322, name: 'Cosmic Power', category: 'Psychic' },
    { value: 323, name: 'Water Spout', category: 'Water' },
    { value: 324, name: 'Signal Beam', category: 'Bug' },
    { value: 325, name: 'Shadow Punch', category: 'Ghost' },
    { value: 326, name: 'Extrasensory', category: 'Psychic' },
    { value: 327, name: 'Sky Uppercut', category: 'Fighting' },
    { value: 328, name: 'Sand Tomb', category: 'Ground' },
    { value: 329, name: 'Sheer Cold', category: 'Ice' },
    { value: 330, name: 'Muddy Water', category: 'Water' },
    { value: 331, name: 'Bullet Seed', category: 'Grass' },
    { value: 332, name: 'Aerial Ace', category: 'Flying' },
    { value: 333, name: 'Icicle Spear', category: 'Ice' },
    { value: 334, name: 'Iron Defense', category: 'Steel' },
    { value: 335, name: 'Block', category: 'Normal' },
    { value: 336, name: 'Howl', category: 'Normal' },
    { value: 337, name: 'Dragon Claw', category: 'Dragon' },
    { value: 338, name: 'Frenzy Plant', category: 'Grass' },
    { value: 339, name: 'Bulk Up', category: 'Fighting' },
    { value: 340, name: 'Bounce', category: 'Flying' },
    { value: 341, name: 'Mud Shot', category: 'Ground' },
    { value: 342, name: 'Poison Tail', category: 'Poison' },
    { value: 343, name: 'Covet', category: 'Normal' },
    { value: 344, name: 'Volt Tackle', category: 'Electric' },
    { value: 345, name: 'Magical Leaf', category: 'Grass' },
    { value: 346, name: 'Water Sport', category: 'Water' },
    { value: 347, name: 'Calm Mind', category: 'Psychic' },
    { value: 348, name: 'Leaf Blade', category: 'Grass' },
    { value: 349, name: 'Dragon Dance', category: 'Dragon' },
    { value: 350, name: 'Rock Blast', category: 'Rock' },
    { value: 351, name: 'Shock Wave', category: 'Electric' },
    { value: 352, name: 'Water Pulse', category: 'Water' },
    { value: 353, name: 'Doom Desire', category: 'Steel' },
    { value: 354, name: 'Psycho Boost', category: 'Psychic' },
  ],
};
