// Local, static, checked-in catalog of Generation III move indices — used
// only to make curated-schema "move" fields show a friendly name/value
// dropdown instead of a raw number box.
//
// SOURCE: compiled from general knowledge of Generation III's move index
// numbering — the same index order documented in tables like Bulbapedia's
// "List of moves by index number in Generation III". This file is NOT
// fetched, scraped, or generated at runtime; it is static source code,
// hand-entered and reviewed like any other file in this repo. Moves 1-251
// are the original Generation I/II move set (unchanged since Gold/Silver,
// identical across every Generation III game); moves 252-354 are the
// Generation III originals, in their documented release order. This was
// compiled from training knowledge of that well-established index list,
// not independently cross-checked against a live external source in this
// session — spot-check anything you rely on for correctness before
// treating it as authoritative. This app's own scripts/generator remain
// the source of truth, not this catalog.

import type { ReferenceCatalog } from '../core/referenceData.js';

export const GEN3_MOVES_CATALOG: ReferenceCatalog = {
  id: 'gen3-moves',
  label: 'Generation III moves',
  description: 'Move name/index lookup for curated schema "move" fields.',
  partial: false,
  sourceNote:
    'Compiled from general knowledge of the well-documented Generation III move ' +
    'index list (moves 1-354, e.g. as catalogued by Bulbapedia\'s "List of moves ' +
    'by index number in Generation III"), not independently cross-checked against ' +
    'a live external source in this session. Covers all 354 Generation III move ' +
    'indices; verify anything you rely on for correctness before treating it as ' +
    'authoritative.',
  entries: [
    { value: 1, name: 'Pound', category: 'Normal' },
    { value: 2, name: 'Karate Chop', category: 'Fighting' },
    { value: 3, name: 'Double Slap', category: 'Normal' },
    { value: 4, name: 'Comet Punch', category: 'Normal' },
    { value: 5, name: 'Mega Punch', category: 'Normal' },
    { value: 6, name: 'Pay Day', category: 'Normal' },
    { value: 7, name: 'Fire Punch', category: 'Fire' },
    { value: 8, name: 'Ice Punch', category: 'Ice' },
    { value: 9, name: 'Thunder Punch', category: 'Electric' },
    { value: 10, name: 'Scratch', category: 'Normal' },
    { value: 11, name: 'Vice Grip', category: 'Normal' },
    { value: 12, name: 'Guillotine', category: 'Normal' },
    { value: 13, name: 'Razor Wind', category: 'Normal' },
    { value: 14, name: 'Swords Dance', category: 'Normal' },
    { value: 15, name: 'Cut', category: 'Normal' },
    { value: 16, name: 'Gust', category: 'Flying' },
    { value: 17, name: 'Wing Attack', category: 'Flying' },
    { value: 18, name: 'Whirlwind', category: 'Normal' },
    { value: 19, name: 'Fly', category: 'Flying' },
    { value: 20, name: 'Bind', category: 'Normal' },
    { value: 21, name: 'Slam', category: 'Normal' },
    { value: 22, name: 'Vine Whip', category: 'Grass' },
    { value: 23, name: 'Stomp', category: 'Normal' },
    { value: 24, name: 'Double Kick', category: 'Fighting' },
    { value: 25, name: 'Mega Kick', category: 'Normal' },
    { value: 26, name: 'Jump Kick', category: 'Fighting' },
    { value: 27, name: 'Rolling Kick', category: 'Fighting' },
    { value: 28, name: 'Sand Attack', category: 'Ground' },
    { value: 29, name: 'Headbutt', category: 'Normal' },
    { value: 30, name: 'Horn Attack', category: 'Normal' },
    { value: 31, name: 'Fury Attack', category: 'Normal' },
    { value: 32, name: 'Horn Drill', category: 'Normal' },
    { value: 33, name: 'Tackle', category: 'Normal' },
    { value: 34, name: 'Body Slam', category: 'Normal' },
    { value: 35, name: 'Wrap', category: 'Normal' },
    { value: 36, name: 'Take Down', category: 'Normal' },
    { value: 37, name: 'Thrash', category: 'Normal' },
    { value: 38, name: 'Double-Edge', category: 'Normal', aliases: ['Double Edge'] },
    { value: 39, name: 'Tail Whip', category: 'Normal' },
    { value: 40, name: 'Poison Sting', category: 'Poison' },
    { value: 41, name: 'Twineedle', category: 'Bug' },
    { value: 42, name: 'Pin Missile', category: 'Bug' },
    { value: 43, name: 'Leer', category: 'Normal' },
    { value: 44, name: 'Bite', category: 'Dark' },
    { value: 45, name: 'Growl', category: 'Normal' },
    { value: 46, name: 'Roar', category: 'Normal' },
    { value: 47, name: 'Sing', category: 'Normal' },
    { value: 48, name: 'Supersonic', category: 'Normal' },
    { value: 49, name: 'Sonic Boom', category: 'Normal' },
    { value: 50, name: 'Disable', category: 'Normal' },
    { value: 51, name: 'Acid', category: 'Poison' },
    { value: 52, name: 'Ember', category: 'Fire' },
    { value: 53, name: 'Flamethrower', category: 'Fire' },
    { value: 54, name: 'Mist', category: 'Ice' },
    { value: 55, name: 'Water Gun', category: 'Water' },
    { value: 56, name: 'Hydro Pump', category: 'Water' },
    { value: 57, name: 'Surf', category: 'Water' },
    { value: 58, name: 'Ice Beam', category: 'Ice' },
    { value: 59, name: 'Blizzard', category: 'Ice' },
    { value: 60, name: 'Psybeam', category: 'Psychic' },
    { value: 61, name: 'Bubble Beam', category: 'Water' },
    { value: 62, name: 'Aurora Beam', category: 'Ice' },
    { value: 63, name: 'Hyper Beam', category: 'Normal' },
    { value: 64, name: 'Peck', category: 'Flying' },
    { value: 65, name: 'Drill Peck', category: 'Flying' },
    { value: 66, name: 'Submission', category: 'Fighting' },
    { value: 67, name: 'Low Kick', category: 'Fighting' },
    { value: 68, name: 'Counter', category: 'Fighting' },
    { value: 69, name: 'Seismic Toss', category: 'Fighting' },
    { value: 70, name: 'Strength', category: 'Normal' },
    { value: 71, name: 'Absorb', category: 'Grass' },
    { value: 72, name: 'Mega Drain', category: 'Grass' },
    { value: 73, name: 'Leech Seed', category: 'Grass' },
    { value: 74, name: 'Growth', category: 'Normal' },
    { value: 75, name: 'Razor Leaf', category: 'Grass' },
    { value: 76, name: 'Solar Beam', category: 'Grass' },
    { value: 77, name: 'Poison Powder', category: 'Poison' },
    { value: 78, name: 'Stun Spore', category: 'Grass' },
    { value: 79, name: 'Sleep Powder', category: 'Grass' },
    { value: 80, name: 'Petal Dance', category: 'Grass' },
    { value: 81, name: 'String Shot', category: 'Bug' },
    { value: 82, name: 'Dragon Rage', category: 'Dragon' },
    { value: 83, name: 'Fire Spin', category: 'Fire' },
    { value: 84, name: 'Thunder Shock', category: 'Electric' },
    { value: 85, name: 'Thunderbolt', category: 'Electric' },
    { value: 86, name: 'Thunder Wave', category: 'Electric' },
    { value: 87, name: 'Thunder', category: 'Electric' },
    { value: 88, name: 'Rock Throw', category: 'Rock' },
    { value: 89, name: 'Earthquake', category: 'Ground' },
    { value: 90, name: 'Fissure', category: 'Ground' },
    { value: 91, name: 'Dig', category: 'Ground' },
    { value: 92, name: 'Toxic', category: 'Poison' },
    { value: 93, name: 'Confusion', category: 'Psychic' },
    { value: 94, name: 'Psychic', category: 'Psychic' },
    { value: 95, name: 'Hypnosis', category: 'Psychic' },
    { value: 96, name: 'Meditate', category: 'Psychic' },
    { value: 97, name: 'Agility', category: 'Psychic' },
    { value: 98, name: 'Quick Attack', category: 'Normal' },
    { value: 99, name: 'Rage', category: 'Normal' },
    { value: 100, name: 'Teleport', category: 'Psychic' },
    { value: 101, name: 'Night Shade' },
    { value: 102, name: 'Mimic' },
    { value: 103, name: 'Screech' },
    { value: 104, name: 'Double Team' },
    { value: 105, name: 'Recover' },
    { value: 106, name: 'Harden' },
    { value: 107, name: 'Minimize' },
    { value: 108, name: 'Smokescreen' },
    { value: 109, name: 'Confuse Ray' },
    { value: 110, name: 'Withdraw' },
    { value: 111, name: 'Defense Curl' },
    { value: 112, name: 'Barrier' },
    { value: 113, name: 'Light Screen' },
    { value: 114, name: 'Haze' },
    { value: 115, name: 'Reflect' },
    { value: 116, name: 'Focus Energy' },
    { value: 117, name: 'Bide' },
    { value: 118, name: 'Metronome' },
    { value: 119, name: 'Mirror Move' },
    { value: 120, name: 'Selfdestruct', aliases: ['Self-Destruct'] },
    { value: 121, name: 'Egg Bomb' },
    { value: 122, name: 'Lick' },
    { value: 123, name: 'Smog' },
    { value: 124, name: 'Sludge' },
    { value: 125, name: 'Bone Club' },
    { value: 126, name: 'Fire Blast' },
    { value: 127, name: 'Waterfall' },
    { value: 128, name: 'Clamp' },
    { value: 129, name: 'Swift' },
    { value: 130, name: 'Skull Bash' },
    { value: 131, name: 'Spike Cannon' },
    { value: 132, name: 'Constrict' },
    { value: 133, name: 'Amnesia' },
    { value: 134, name: 'Kinesis' },
    { value: 135, name: 'Soft-Boiled', aliases: ['Soft Boiled'] },
    { value: 136, name: 'High Jump Kick' },
    { value: 137, name: 'Glare' },
    { value: 138, name: 'Dream Eater' },
    { value: 139, name: 'Poison Gas' },
    { value: 140, name: 'Barrage' },
    { value: 141, name: 'Leech Life' },
    { value: 142, name: 'Lovely Kiss' },
    { value: 143, name: 'Sky Attack' },
    { value: 144, name: 'Transform' },
    { value: 145, name: 'Bubble' },
    { value: 146, name: 'Dizzy Punch' },
    { value: 147, name: 'Spore' },
    { value: 148, name: 'Flash' },
    { value: 149, name: 'Psywave' },
    { value: 150, name: 'Splash' },
    { value: 151, name: 'Acid Armor' },
    { value: 152, name: 'Crabhammer' },
    { value: 153, name: 'Explosion' },
    { value: 154, name: 'Fury Swipes' },
    { value: 155, name: 'Bonemerang' },
    { value: 156, name: 'Rest' },
    { value: 157, name: 'Rock Slide' },
    { value: 158, name: 'Hyper Fang' },
    { value: 159, name: 'Sharpen' },
    { value: 160, name: 'Conversion' },
    { value: 161, name: 'Tri Attack' },
    { value: 162, name: 'Super Fang' },
    { value: 163, name: 'Slash' },
    { value: 164, name: 'Substitute' },
    { value: 165, name: 'Struggle' },
    { value: 166, name: 'Sketch' },
    { value: 167, name: 'Triple Kick' },
    { value: 168, name: 'Thief' },
    { value: 169, name: 'Spider Web' },
    { value: 170, name: 'Mind Reader' },
    { value: 171, name: 'Nightmare' },
    { value: 172, name: 'Flame Wheel' },
    { value: 173, name: 'Snore' },
    { value: 174, name: 'Curse' },
    { value: 175, name: 'Flail' },
    { value: 176, name: 'Conversion 2', aliases: ['Conversion2'] },
    { value: 177, name: 'Aeroblast' },
    { value: 178, name: 'Cotton Spore' },
    { value: 179, name: 'Reversal' },
    { value: 180, name: 'Spite' },
    { value: 181, name: 'Powder Snow' },
    { value: 182, name: 'Protect' },
    { value: 183, name: 'Mach Punch' },
    { value: 184, name: 'Scary Face' },
    { value: 185, name: 'Faint Attack', aliases: ['Feint Attack'] },
    { value: 186, name: 'Sweet Kiss' },
    { value: 187, name: 'Belly Drum' },
    { value: 188, name: 'Sludge Bomb' },
    { value: 189, name: 'Mud-Slap', aliases: ['Mud Slap'] },
    { value: 190, name: 'Octazooka' },
    { value: 191, name: 'Spikes' },
    { value: 192, name: 'Zap Cannon' },
    { value: 193, name: 'Foresight' },
    { value: 194, name: 'Destiny Bond' },
    { value: 195, name: 'Perish Song' },
    { value: 196, name: 'Icy Wind' },
    { value: 197, name: 'Detect' },
    { value: 198, name: 'Bone Rush' },
    { value: 199, name: 'Lock-On' },
    { value: 200, name: 'Outrage' },
    { value: 201, name: 'Sandstorm' },
    { value: 202, name: 'Giga Drain' },
    { value: 203, name: 'Endure' },
    { value: 204, name: 'Charm' },
    { value: 205, name: 'Rollout' },
    { value: 206, name: 'False Swipe' },
    { value: 207, name: 'Swagger' },
    { value: 208, name: 'Milk Drink' },
    { value: 209, name: 'Spark' },
    { value: 210, name: 'Fury Cutter' },
    { value: 211, name: 'Steel Wing' },
    { value: 212, name: 'Mean Look' },
    { value: 213, name: 'Attract' },
    { value: 214, name: 'Sleep Talk' },
    { value: 215, name: 'Heal Bell' },
    { value: 216, name: 'Return' },
    { value: 217, name: 'Present' },
    { value: 218, name: 'Frustration' },
    { value: 219, name: 'Safeguard' },
    { value: 220, name: 'Pain Split' },
    { value: 221, name: 'Sacred Fire' },
    { value: 222, name: 'Magnitude' },
    { value: 223, name: 'Dynamic Punch' },
    { value: 224, name: 'Megahorn' },
    { value: 225, name: 'Dragon Breath' },
    { value: 226, name: 'Baton Pass' },
    { value: 227, name: 'Encore' },
    { value: 228, name: 'Pursuit' },
    { value: 229, name: 'Rapid Spin' },
    { value: 230, name: 'Sweet Scent' },
    { value: 231, name: 'Iron Tail' },
    { value: 232, name: 'Metal Claw' },
    { value: 233, name: 'Vital Throw' },
    { value: 234, name: 'Morning Sun' },
    { value: 235, name: 'Synthesis' },
    { value: 236, name: 'Moonlight' },
    { value: 237, name: 'Hidden Power' },
    { value: 238, name: 'Cross Chop' },
    { value: 239, name: 'Twister' },
    { value: 240, name: 'Rain Dance' },
    { value: 241, name: 'Sunny Day' },
    { value: 242, name: 'Crunch' },
    { value: 243, name: 'Mirror Coat' },
    { value: 244, name: 'Psych Up' },
    { value: 245, name: 'Extreme Speed' },
    { value: 246, name: 'Ancient Power' },
    { value: 247, name: 'Shadow Ball' },
    { value: 248, name: 'Future Sight' },
    { value: 249, name: 'Rock Smash' },
    { value: 250, name: 'Whirlpool' },
    { value: 251, name: 'Beat Up' },
    { value: 252, name: 'Fake Out' },
    { value: 253, name: 'Uproar' },
    { value: 254, name: 'Stockpile' },
    { value: 255, name: 'Spit Up' },
    { value: 256, name: 'Swallow' },
    { value: 257, name: 'Heat Wave' },
    { value: 258, name: 'Hail' },
    { value: 259, name: 'Torment' },
    { value: 260, name: 'Flatter' },
    { value: 261, name: 'Will-O-Wisp', aliases: ['Will O Wisp'] },
    { value: 262, name: 'Memento' },
    { value: 263, name: 'Facade' },
    { value: 264, name: 'Focus Punch' },
    { value: 265, name: 'Smelling Salts' },
    { value: 266, name: 'Follow Me' },
    { value: 267, name: 'Nature Power' },
    { value: 268, name: 'Charge' },
    { value: 269, name: 'Taunt' },
    { value: 270, name: 'Helping Hand' },
    { value: 271, name: 'Trick' },
    { value: 272, name: 'Role Play' },
    { value: 273, name: 'Wish' },
    { value: 274, name: 'Assist' },
    { value: 275, name: 'Ingrain' },
    { value: 276, name: 'Superpower' },
    { value: 277, name: 'Magic Coat' },
    { value: 278, name: 'Recycle' },
    { value: 279, name: 'Revenge' },
    { value: 280, name: 'Brick Break' },
    { value: 281, name: 'Yawn' },
    { value: 282, name: 'Knock Off' },
    { value: 283, name: 'Endeavor' },
    { value: 284, name: 'Eruption' },
    { value: 285, name: 'Skill Swap' },
    { value: 286, name: 'Imprison' },
    { value: 287, name: 'Refresh' },
    { value: 288, name: 'Grudge' },
    { value: 289, name: 'Snatch' },
    { value: 290, name: 'Secret Power' },
    { value: 291, name: 'Dive' },
    { value: 292, name: 'Arm Thrust' },
    { value: 293, name: 'Camouflage' },
    { value: 294, name: 'Tail Glow' },
    { value: 295, name: 'Luster Purge' },
    { value: 296, name: 'Mist Ball' },
    { value: 297, name: 'Feather Dance', aliases: ['FeatherDance'] },
    { value: 298, name: 'Teeter Dance' },
    { value: 299, name: 'Blaze Kick' },
    { value: 300, name: 'Mud Sport' },
    { value: 301, name: 'Ice Ball' },
    { value: 302, name: 'Needle Arm' },
    { value: 303, name: 'Slack Off' },
    { value: 304, name: 'Hyper Voice' },
    { value: 305, name: 'Poison Fang' },
    { value: 306, name: 'Crush Claw' },
    { value: 307, name: 'Blast Burn' },
    { value: 308, name: 'Hydro Cannon' },
    { value: 309, name: 'Meteor Mash' },
    { value: 310, name: 'Astonish' },
    { value: 311, name: 'Weather Ball' },
    { value: 312, name: 'Aromatherapy' },
    { value: 313, name: 'Fake Tears' },
    { value: 314, name: 'Air Cutter' },
    { value: 315, name: 'Overheat' },
    { value: 316, name: 'Odor Sleuth' },
    { value: 317, name: 'Rock Tomb' },
    { value: 318, name: 'Silver Wind' },
    { value: 319, name: 'Metal Sound' },
    { value: 320, name: 'Grass Whistle', aliases: ['GrassWhistle'] },
    { value: 321, name: 'Tickle' },
    { value: 322, name: 'Cosmic Power' },
    { value: 323, name: 'Water Spout' },
    { value: 324, name: 'Signal Beam' },
    { value: 325, name: 'Shadow Punch' },
    { value: 326, name: 'Extrasensory' },
    { value: 327, name: 'Sky Uppercut' },
    { value: 328, name: 'Sand Tomb' },
    { value: 329, name: 'Sheer Cold' },
    { value: 330, name: 'Muddy Water' },
    { value: 331, name: 'Bullet Seed' },
    { value: 332, name: 'Aerial Ace' },
    { value: 333, name: 'Icicle Spear' },
    { value: 334, name: 'Iron Defense' },
    { value: 335, name: 'Block' },
    { value: 336, name: 'Howl' },
    { value: 337, name: 'Dragon Claw' },
    { value: 338, name: 'Frenzy Plant' },
    { value: 339, name: 'Bulk Up' },
    { value: 340, name: 'Bounce' },
    { value: 341, name: 'Mud Shot' },
    { value: 342, name: 'Poison Tail' },
    { value: 343, name: 'Covet' },
    { value: 344, name: 'Volt Tackle' },
    { value: 345, name: 'Magical Leaf' },
    { value: 346, name: 'Water Sport' },
    { value: 347, name: 'Calm Mind' },
    { value: 348, name: 'Leaf Blade' },
    { value: 349, name: 'Dragon Dance' },
    { value: 350, name: 'Rock Blast' },
    { value: 351, name: 'Shock Wave' },
    { value: 352, name: 'Water Pulse' },
    { value: 353, name: 'Doom Desire' },
    { value: 354, name: 'Psycho Boost' },
  ],
};
