// Data model for the FireRed BoxName Workbench.
//
// Every text field below is an opaque string as far as this app is concerned.
// Nothing in the codebase decodes or transforms these values on its own. Text
// is user-typed, user-imported, chosen from a fixed template, or — once a
// generator adapter exists in a future branch — returned from an existing
// local script treated as source of truth. It is stored and displayed
// verbatim, with provenance, either way.

export type ProjectStatus = 'draft' | 'in-review' | 'reviewed' | 'exported';
export type Mode = 'documentation' | 'checklist-review';
export type ChecklistState =
  | 'unchecked'
  | 'confirmed'
  | 'not-applicable'
  | 'needs-follow-up';

export type Severity = 'info' | 'warning' | 'error';

export type FindingRule =
  | 'missing-field'
  | 'empty-field'
  | 'inconsistent-label'
  | 'line-length'
  | 'line-count'
  | 'unsupported-glyph'
  | 'ambiguous-glyph'
  | 'duplicate-item'
  | 'incomplete-assumptions';

export type TargetKind = 'metadata' | 'checklist' | 'note' | 'importedBlock';

export interface GameMetadata {
  schemaVersion: 1;
  /** Locked to FireRed by product design. */
  game: 'FireRed';
  revisionLabel: string;
  languageLabel: string;
  /** Organizational title for the project. Display label only. */
  projectTitle: string;
  mode: Mode;
  createdAt: string;
  updatedAt: string;
}

export interface ChecklistItem {
  id: string;
  templateKey?: string;
  prompt: string;
  category: string;
  state: ChecklistState;
  note: string;
  required: boolean;
}

export interface UserNote {
  id: string;
  sectionTitle: string;
  body: string;
  order: number;
}

/**
 * Where an imported text block came from.
 *
 * `external-local-tool` is a user-selectable provenance LABEL only. The user may
 * mark a block as having come from an external local tool and document that tool,
 * but the app never runs, calls, embeds, or integrates with any external tool.
 * Text still arrives only via manual paste or file import, stored verbatim.
 * This is also the type used for manually pasted-back generator output: the
 * user runs their own generator by hand and pastes the result in.
 *
 * `mock-output` marks a block saved from the Action Builder's mock generator
 * (see MockGeneratedOutput below). It is placeholder output only — the mock
 * adapter never computes real game-related content — but it is still stored
 * and displayed verbatim like any other block, with its own provenance.
 *
 * `filled-script` marks a block saved from fillScriptFromSchema's output —
 * this app's own conservative, header-only text substitution. It is stored
 * and displayed verbatim, like any other block; the app never runs it.
 */
export type TextSourceType =
  | 'manual-paste'
  | 'file-import'
  | 'demo-fixture'
  | 'external-local-tool'
  | 'mock-output'
  | 'filled-script';

export interface TextSource {
  type: TextSourceType;
  /** Human-readable, user-editable label for the source. */
  label: string;
  importedAt: string;
  /** Optional originating filename (for file-import). */
  filename?: string;
  /** Optional user-editable notes about the source/provenance. */
  notes?: string;
  /** Provenance schema version, for future-proofing this metadata. */
  schemaVersion: number;

  // --- external-local-tool documentation fields (metadata only) ---
  // These are user-typed documentation strings. They are NEVER executed, parsed,
  // fetched, or interpreted; the app performs no external-tool invocation.
  toolName?: string;
  toolVersion?: string;
  toolUrl?: string;
  invocationNotes?: string;

  // --- mock-output / filled-script / manual-paste-back provenance fields ---
  // (metadata only). Record which action and script informed this block.
  // Never read back to compute anything; the app only displays these strings.
  actionId?: string;
  actionLabel?: string;
  generatedBy?: string;
  /** Id of the ScriptFile this block's text was derived from or pasted for, if any. */
  scriptId?: string;
}

export interface ImportedTextBlock {
  id: string;
  title: string;
  categoryLabel: string;
  revisionLabel: string;
  /** Stored verbatim. Never modified or generated by the app. */
  rawText: string;
  /** User notes about the block's content (distinct from source.notes). */
  notes: string;
  /** Provenance: where this text came from. */
  source: TextSource;
}

export interface FindingTarget {
  kind: TargetKind;
  refId?: string;
  line?: number;
  column?: number;
}

export interface Finding {
  id: string;
  rule: FindingRule;
  severity: Severity;
  target: FindingTarget;
  message: string;
  acknowledged: boolean;
  ackNote?: string;
}

export interface ValidationResult {
  runAt: string;
  findings: Finding[];
}

export interface ValidationSettings {
  maxLineLength: number;
  expectedLineMin?: number;
  expectedLineMax?: number;
  /** Explicit allow-list of display glyphs. Empty/undefined => printable ASCII. */
  allowedGlyphs?: string;
  countMode: 'codepoints' | 'utf16';
}

export interface Project {
  schemaVersion: 1;
  id: string;
  metadata: GameMetadata;
  checklist: ChecklistItem[];
  notes: UserNote[];
  importedBlocks: ImportedTextBlock[];
  settings: ValidationSettings;
  latestValidation: ValidationResult | null;
  projectStatus: ProjectStatus;
  /** Local Script Library (Manage Scripts) — developer-only, informational. See ScriptFile below. */
  scripts: ScriptFile[];
  /** Hand-reviewed action schemas curated from scanned scripts. See CuratedActionSchema below. */
  curatedSchemas: CuratedActionSchema[];
  /** Batch "import script folder" operations. See ScriptPack below. */
  scriptPacks: ScriptPack[];
}

export interface ReviewSummary {
  totalItems: number;
  confirmed: number;
  notApplicable: number;
  needsFollowUp: number;
  requiredOutstanding: number;
}

export interface ReportExport {
  schemaVersion: 1;
  metadata: GameMetadata;
  checklist: ChecklistItem[];
  notes: UserNote[];
  importedBlocks: ImportedTextBlock[];
  latestValidation: ValidationResult | null;
  projectStatus: ProjectStatus;
  reviewSummary: ReviewSummary;
  exportedAt: string;
}

export const DEFAULT_VALIDATION_SETTINGS: ValidationSettings = {
  maxLineLength: 30,
  countMode: 'codepoints',
};

// --- Action Builder (Phase 1: mock output only) -----------------------------
//
// These types describe the Action Builder workflow: a user picks a known
// FireRed action template (see src/templates/action-templates.ts), fills in
// its fields, and runs the MOCK generator adapter (src/core/generatorAdapter.ts)
// to get placeholder box-name rows. Nothing here computes real game-related
// output; ActionInput values are opaque, user-supplied field values, and
// MockGeneratedOutput.rows always carry a fixed placeholder string.

/** A single field's value, as entered by the user in the Action Builder. */
export type ActionFieldValue = string | number | boolean;

/** A concrete, renderable Action Builder field shape — no 'unknown' variant. */
export type ActionFieldType = 'text' | 'number' | 'select' | 'checkbox';

/** A neutral, user-facing option for a 'select' field. */
export interface ActionFieldOption {
  value: string;
  label: string;
}

/** The user's filled-in inputs for one action template, before generation. */
export interface ActionInput {
  actionId: string;
  revisionLabel: string;
  values: Record<string, ActionFieldValue>;
}

/** One row of a box-name sheet: a box, its display label, and placeholder text. */
export interface BoxNameRow {
  boxLabel: string;
  rowLabel: string;
  /** Always a fixed placeholder string (e.g. "PLACEHLD") in this phase. */
  text: string;
}

/** The result of running the mock generator adapter over an ActionInput. */
export interface MockGeneratedOutput {
  actionId: string;
  actionLabel: string;
  revisionLabel: string;
  generatedAt: string;
  rows: readonly BoxNameRow[];
  /** Always true — a visible marker that this is placeholder, not real, output. */
  isMock: true;
}

// --- Script Library (developer-only, informational) -------------------------
//
// These types describe local script INSPECTION only. A ScriptFile's rawText
// is stored and displayed verbatim, never executed, assembled, or fed to a
// generator. The scanner (src/core/scriptScanner.ts) reads that text as text
// and produces a best-effort, human-reviewed DRAFT (ScriptScanResult /
// DraftActionSchema) — never a live action template, never real output.

export type CandidateConfidence = 'high' | 'medium' | 'low';

/** A rough, heuristic guess at what kind of Action Builder field a candidate resembles. */
export type InferredFieldKind = 'number' | 'checkbox' | 'select' | 'text' | 'unknown';

/** A slice of a script's text, split around the first `@@` marker line (if any). */
export interface ScriptSection {
  kind: 'header' | 'body';
  startLine: number;
  endLine: number;
  text: string;
}

/** A candidate variable assignment found in a script's header, before `@@`. */
export interface VariableCandidate {
  name: string;
  rawValue: string;
  /** 1-based line number within the script's header section. */
  line: number;
  /** Trailing same-line comment, or the preceding full-line comment, if any. */
  nearbyComment?: string;
  /** A recognized `@input:xxx` tag found on or near this candidate, if any. */
  annotation?: string;
  /**
   * The bare hint value from a recognized `@input:xxx` annotation (e.g. "move"
   * for `@input:move`) — a clean, structured echo of `annotation` for display
   * and future cross-referencing. Not a lookup into any move/item database.
   */
  inputHint?: string;
  inferredType: InferredFieldKind;
  confidence: CandidateConfidence;
  /**
   * True when a preceding full-line comment in the header (e.g. "Do not
   * modify these values") marked this and subsequent header assignments as
   * internal/helper values rather than user-facing input. Informational only
   * — the scanner still reports these for transparency, but the schema
   * builder should not include them by default.
   */
  internal: boolean;
}

/**
 * A recognized `@key = value` or `@@key = value` header directive line —
 * distinct from the exact `@@` marker line (which has no `= value` at all)
 * and from candidate variable assignments. Metadata/documentation only,
 * never exposed as a curated schema field.
 */
export interface ScriptDirective {
  key: string;
  rawValue: string;
  /** 1-based line number within the script's header section. */
  line: number;
}

/** The result of scanning one ScriptFile. Informational only. */
export interface ScriptScanResult {
  scriptId: string;
  scannedAt: string;
  /** 1-based line number of the first `@@` marker, or null if none was found. */
  markerLine: number | null;
  sections: ScriptSection[];
  candidates: VariableCandidate[];
  /** Every recognized header directive line (e.g. title/author/exit), in order. */
  directives: ScriptDirective[];
  /** Convenience shortcuts, unquoted, for the common `title`/`author`/`exit` directive keys. */
  title?: string;
  author?: string;
  exit?: string;
}

/** One field in a draft action schema, derived from a single VariableCandidate. */
export interface DraftActionField {
  key: string;
  label: string;
  inferredType: InferredFieldKind;
  confidence: CandidateConfidence;
  sourceLine: number;
  notes?: string;
}

/**
 * A draft, auto-generated action schema derived from a script scan. `isDraft`
 * is always true: this is a starting point for a human to hand-edit into a
 * CuratedActionSchema (below) — it is never automatically wired into
 * ACTION_TEMPLATES or any generator on its own.
 */
export interface DraftActionSchema {
  scriptId: string;
  scriptFilename: string;
  generatedAt: string;
  fields: DraftActionField[];
  isDraft: true;
}

// --- Game-target compatibility model -----------------------------------------
//
// A GameTarget records which game/language/revision a script or curated
// schema was written for — informational/filtering metadata only. Nothing
// here invokes a generator, reads a ROM/save, or verifies compatibility
// against real game data; "compatible" only ever means "the recorded
// metadata matches." See core/gameTarget.ts for the enum lists and pure
// label/match/compatibility/sort helpers. "Unknown" is a first-class, valid
// value everywhere — existing scripts/schemas/packs that predate this model
// migrate to it, never silently to a guessed real value.

export type TargetGame = 'FireRed' | 'LeafGreen' | 'Unknown';
export type TargetLanguage =
  | 'English'
  | 'Japanese'
  | 'Spanish'
  | 'French'
  | 'German'
  | 'Italian'
  | 'Korean'
  | 'Unknown';
export type TargetRevision = '1.0' | '1.1' | 'Unknown';

export interface GameTarget {
  game: TargetGame;
  language: TargetLanguage;
  revision: TargetRevision;
  /** Optional free-text region label (documentation only, e.g. "PAL"). */
  regionLabel?: string;
  notes?: string;
}

/** A locally-imported `.txt` action script, kept for inspection only. */
export interface ScriptFile {
  id: string;
  filename: string;
  /** Stored verbatim. Never modified, executed, or transformed by the app. */
  rawText: string;
  importedAt: string;
  notes?: string;
  /** Most recent scan of this script's rawText, if the user has run one. */
  lastScan?: ScriptScanResult;
  /** Path relative to the imported folder root, if imported as part of a script pack. */
  relativePath?: string;
  /** Id of the ScriptPack this script was imported as part of, if any. */
  packId?: string;
  /** Overrides the owning pack's defaultTarget for this specific script, if set. See GameTarget below. */
  targetOverride?: GameTarget;
}

// --- Script packs (batch "import script folder") ----------------------------
//
// A ScriptPack records one folder-import operation: a name, when it happened,
// the top-level folder name (if the browser reported one), and which scripts
// (already stored verbatim in Project.scripts) came from it. It carries no
// script text of its own and never mutates the scripts it references.

export interface ScriptPack {
  id: string;
  name: string;
  importedAt: string;
  sourceFolderName?: string;
  /** Default target for scripts in this pack, unless a script sets its own targetOverride. See GameTarget below. */
  defaultTarget: GameTarget;
  targetNotes?: string;
  /** Ids into Project.scripts for the scripts imported as part of this pack. */
  scriptIds: readonly string[];
}

// --- Curated action schemas (mock mode only) --------------------------------
//
// A CuratedActionSchema is a HAND-REVIEWED field mapping for a script,
// distinct from the auto-generated DraftActionSchema above: it carries a
// review status, a script-variable mapping per field, and human-facing help
// text/warnings. It lives in Project.curatedSchemas — separate from the
// built-in mock ACTION_TEMPLATES catalog. The Action Builder can select one
// in mock mode (selecting one only changes which fields render and validate,
// never what MockGeneratorAdapter computes) AND, when it is linked to an
// imported script, use it to conservatively fill that script's header (see
// FilledScriptResult below) for the user to copy into their OWN external
// generator. No generator is ever invoked by this app.

export type CuratedSchemaStatus = 'draft' | 'reviewed' | 'disabled';

/** One reviewed field: a mapping from a script variable to an Action Builder field. */
export interface CuratedSchemaField {
  key: string;
  label: string;
  type: ActionFieldType;
  required: boolean;
  /** The script variable this field maps to (usually a VariableCandidate.name). */
  variableName: string;
  helpText?: string;
  warnings?: readonly string[];
  /** Only meaningful for type 'select'. Values are neutral placeholders. */
  options?: readonly ActionFieldOption[];
  defaultValue?: ActionFieldValue;
  /**
   * A clean input-kind hint carried over from a scanner annotation (e.g.
   * "move" from `@input:move`) — informational only, never looked up against
   * any move/item database.
   */
  inputHint?: string;
  /** Only meaningful for type 'number'. Display-only range hint — never enforced or evaluated. */
  min?: number;
  max?: number;
}

/** A human-reviewed action schema curated from a scanned local script. */
export interface CuratedActionSchema {
  id: string;
  label: string;
  description: string;
  /** Stable action concept shared across target-specific variants (e.g. "teach-any-move"). Distinct from `id`, which stays unique per variant. */
  actionKey?: string;
  /** Which game/language/revision this specific schema variant targets. Unknown/Mixed until the user sets it. */
  target: GameTarget;
  scriptId?: string;
  scriptFilename?: string;
  /** Empty = supports any revision. Free-text label matching, distinct from and predates the structured `target` field above. */
  supportedRevisionLabels: readonly string[];
  fields: readonly CuratedSchemaField[];
  status: CuratedSchemaStatus;
}

// --- Conservative script filling (manual generator workflow) ----------------
//
// fillScriptFromSchema (src/core/scriptFiller.ts) only ever replaces the
// VALUE portion of a simple `name = value` line in a script's HEADER, for
// variables a CuratedActionSchema explicitly maps — never body lines, never
// inferred variables, never expression evaluation. It produces text for a
// human to copy into their OWN external generator; this app never invokes
// that generator itself.

/** One line changed by fillScriptFromSchema. */
export interface FilledLineChange {
  /** 1-based line number in the original script text. */
  line: number;
  variableName: string;
  before: string;
  after: string;
}

export interface FilledScriptResult {
  originalScriptText: string;
  filledScriptText: string;
  changedLines: readonly FilledLineChange[];
  warnings: readonly string[];
  errors: readonly string[];
}

// --- Manual generator output paste-back -------------------------------------
//
// The user runs their own external generator by hand and pastes its output
// back in. It is stored and displayed verbatim. Real generator output mixes
// several kinds of lines — encoded command lines, an "All commands" section,
// a "Raw data" section, and a "Box N: ..." box-name section — so the
// box-name sheet presenter must extract only the `Box N:` lines rather than
// treating every pasted line as a box-name row. Parsing below is for
// DISPLAY ONLY and never changes the saved rawText.

/** One recognized `Box N: ...` line from pasted generator output. */
export interface ParsedBoxNameRow {
  boxNumber: number;
  /** The original `Box N: ...` line, verbatim. */
  rawLine: string;
  /** The spaced-out display text before the bracketed compact form, trimmed for display only. */
  spacedDisplay: string;
  /** The compact bracketed form (e.g. "[/?UnFE3n]" -> "/?UnFE3n"), or null if the line had none. */
  compactText: string | null;
}

/** The result of parsing pasted generator output for its box-name section. */
export interface ParsedGeneratorOutput {
  /** The full pasted text, unchanged. */
  rawText: string;
  rows: readonly ParsedBoxNameRow[];
  warnings: readonly string[];
}
