// Data model for the FireRed BoxName Workbench.
//
// Every text field below is an opaque string as far as this app is concerned.
// Nothing in the codebase decodes or transforms these values on its own. Text
// is user-typed, user-imported, chosen from a fixed template, or — once a
// generator adapter exists in a future branch — returned from an existing
// local script treated as source of truth. It is stored and displayed
// verbatim, with provenance, either way.

export type ProjectStatus = 'draft' | 'in-review' | 'reviewed' | 'exported';
export type Mode = 'documentation' | 'checklist-review';
export type ChecklistState =
  | 'unchecked'
  | 'confirmed'
  | 'not-applicable'
  | 'needs-follow-up';

export type Severity = 'info' | 'warning' | 'error';

export type FindingRule =
  | 'missing-field'
  | 'empty-field'
  | 'inconsistent-label'
  | 'line-length'
  | 'line-count'
  | 'unsupported-glyph'
  | 'ambiguous-glyph'
  | 'duplicate-item'
  | 'incomplete-assumptions';

export type TargetKind = 'metadata' | 'checklist' | 'note' | 'importedBlock';

export interface GameMetadata {
  schemaVersion: 1;
  /** Locked to FireRed by product design. */
  game: 'FireRed';
  revisionLabel: string;
  languageLabel: string;
  /** Organizational title for the project. Display label only. */
  projectTitle: string;
  mode: Mode;
  createdAt: string;
  updatedAt: string;
}

export interface ChecklistItem {
  id: string;
  templateKey?: string;
  prompt: string;
  category: string;
  state: ChecklistState;
  note: string;
  required: boolean;
}

export interface UserNote {
  id: string;
  sectionTitle: string;
  body: string;
  order: number;
}

/**
 * Where an imported text block came from.
 *
 * `external-local-tool` is a user-selectable provenance LABEL only. The user may
 * mark a block as having come from an external local tool and document that tool,
 * but the app never runs, calls, embeds, or integrates with any external tool.
 * Text still arrives only via manual paste or file import, stored verbatim.
 *
 * `mock-output` marks a block saved from the Action Builder's mock generator
 * (see MockGeneratedOutput below). It is placeholder output only — the mock
 * adapter never computes real game-related content — but it is still stored
 * and displayed verbatim like any other block, with its own provenance.
 */
export type TextSourceType = 'manual-paste' | 'file-import' | 'demo-fixture' | 'external-local-tool' | 'mock-output';

export interface TextSource {
  type: TextSourceType;
  /** Human-readable, user-editable label for the source. */
  label: string;
  importedAt: string;
  /** Optional originating filename (for file-import). */
  filename?: string;
  /** Optional user-editable notes about the source/provenance. */
  notes?: string;
  /** Provenance schema version, for future-proofing this metadata. */
  schemaVersion: number;

  // --- external-local-tool documentation fields (metadata only) ---
  // These are user-typed documentation strings. They are NEVER executed, parsed,
  // fetched, or interpreted; the app performs no external-tool invocation.
  toolName?: string;
  toolVersion?: string;
  toolUrl?: string;
  invocationNotes?: string;

  // --- mock-output provenance fields (metadata only) ---
  // Record which placeholder action template produced a mock-output block.
  // Never read back to compute anything; the app only displays these strings.
  actionId?: string;
  actionLabel?: string;
  generatedBy?: string;
}

export interface ImportedTextBlock {
  id: string;
  title: string;
  categoryLabel: string;
  revisionLabel: string;
  /** Stored verbatim. Never modified or generated by the app. */
  rawText: string;
  /** User notes about the block's content (distinct from source.notes). */
  notes: string;
  /** Provenance: where this text came from. */
  source: TextSource;
}

export interface FindingTarget {
  kind: TargetKind;
  refId?: string;
  line?: number;
  column?: number;
}

export interface Finding {
  id: string;
  rule: FindingRule;
  severity: Severity;
  target: FindingTarget;
  message: string;
  acknowledged: boolean;
  ackNote?: string;
}

export interface ValidationResult {
  runAt: string;
  findings: Finding[];
}

export interface ValidationSettings {
  maxLineLength: number;
  expectedLineMin?: number;
  expectedLineMax?: number;
  /** Explicit allow-list of display glyphs. Empty/undefined => printable ASCII. */
  allowedGlyphs?: string;
  countMode: 'codepoints' | 'utf16';
}

export interface Project {
  schemaVersion: 1;
  id: string;
  metadata: GameMetadata;
  checklist: ChecklistItem[];
  notes: UserNote[];
  importedBlocks: ImportedTextBlock[];
  settings: ValidationSettings;
  latestValidation: ValidationResult | null;
  projectStatus: ProjectStatus;
  /** Local Script Library — developer-only, informational. See ScriptFile below. */
  scripts: ScriptFile[];
}

export interface ReviewSummary {
  totalItems: number;
  confirmed: number;
  notApplicable: number;
  needsFollowUp: number;
  requiredOutstanding: number;
}

export interface ReportExport {
  schemaVersion: 1;
  metadata: GameMetadata;
  checklist: ChecklistItem[];
  notes: UserNote[];
  importedBlocks: ImportedTextBlock[];
  latestValidation: ValidationResult | null;
  projectStatus: ProjectStatus;
  reviewSummary: ReviewSummary;
  exportedAt: string;
}

export const DEFAULT_VALIDATION_SETTINGS: ValidationSettings = {
  maxLineLength: 30,
  countMode: 'codepoints',
};

// --- Action Builder (Phase 1: mock output only) -----------------------------
//
// These types describe the Action Builder workflow: a user picks a known
// FireRed action template (see src/templates/action-templates.ts), fills in
// its fields, and runs the MOCK generator adapter (src/core/generatorAdapter.ts)
// to get placeholder box-name rows. Nothing here computes real game-related
// output; ActionInput values are opaque, user-supplied field values, and
// MockGeneratedOutput.rows always carry a fixed placeholder string.

/** A single field's value, as entered by the user in the Action Builder. */
export type ActionFieldValue = string | number | boolean;

/** The user's filled-in inputs for one action template, before generation. */
export interface ActionInput {
  actionId: string;
  revisionLabel: string;
  values: Record<string, ActionFieldValue>;
}

/** One row of a box-name sheet: a box, its display label, and placeholder text. */
export interface BoxNameRow {
  boxLabel: string;
  rowLabel: string;
  /** Always a fixed placeholder string (e.g. "PLACEHLD") in this phase. */
  text: string;
}

/** The result of running the mock generator adapter over an ActionInput. */
export interface MockGeneratedOutput {
  actionId: string;
  actionLabel: string;
  revisionLabel: string;
  generatedAt: string;
  rows: readonly BoxNameRow[];
  /** Always true — a visible marker that this is placeholder, not real, output. */
  isMock: true;
}

// --- Script Library (developer-only, informational) -------------------------
//
// These types describe local script INSPECTION only. A ScriptFile's rawText
// is stored and displayed verbatim, never executed, assembled, or fed to a
// generator. The scanner (src/core/scriptScanner.ts) reads that text as text
// and produces a best-effort, human-reviewed DRAFT (ScriptScanResult /
// DraftActionSchema) — never a live action template, never real output.

export type CandidateConfidence = 'high' | 'medium' | 'low';

/** A rough, heuristic guess at what kind of Action Builder field a candidate resembles. */
export type InferredFieldKind = 'number' | 'checkbox' | 'select' | 'text' | 'unknown';

/** A slice of a script's text, split around the first `@@` marker line (if any). */
export interface ScriptSection {
  kind: 'header' | 'body';
  startLine: number;
  endLine: number;
  text: string;
}

/** A candidate variable assignment found in a script's header, before `@@`. */
export interface VariableCandidate {
  name: string;
  rawValue: string;
  /** 1-based line number within the script's header section. */
  line: number;
  /** Trailing same-line comment, or the preceding full-line comment, if any. */
  nearbyComment?: string;
  /** A recognized `@input:xxx` tag found on or near this candidate, if any. */
  annotation?: string;
  inferredType: InferredFieldKind;
  confidence: CandidateConfidence;
}

/** The result of scanning one ScriptFile. Informational only. */
export interface ScriptScanResult {
  scriptId: string;
  scannedAt: string;
  /** 1-based line number of the first `@@` marker, or null if none was found. */
  markerLine: number | null;
  sections: ScriptSection[];
  candidates: VariableCandidate[];
}

/** One field in a draft action schema, derived from a single VariableCandidate. */
export interface DraftActionField {
  key: string;
  label: string;
  inferredType: InferredFieldKind;
  confidence: CandidateConfidence;
  sourceLine: number;
  notes?: string;
}

/**
 * A draft, human-reviewable action schema derived from a script scan (or
 * hand-curated and imported back in). `isDraft` is always true: this is
 * never automatically wired into ACTION_TEMPLATES or any generator.
 */
export interface DraftActionSchema {
  scriptId: string;
  scriptFilename: string;
  generatedAt: string;
  fields: DraftActionField[];
  isDraft: true;
}

/** A locally-imported `.txt` action script, kept for inspection only. */
export interface ScriptFile {
  id: string;
  filename: string;
  /** Stored verbatim. Never modified, executed, or transformed by the app. */
  rawText: string;
  importedAt: string;
  notes?: string;
  /** Most recent scan of this script's rawText, if the user has run one. */
  lastScan?: ScriptScanResult;
  /** A hand-curated schema imported back in for review; still informational only. */
  curatedSchema?: DraftActionSchema;
}
